"""Reference data for checking the nautical almanac (js, from Meeus's Astronomical Algorithms): Sun, Moon, the navigational stars, sidereal time.
Writes almanac-ref.json beside this script; the almanac's figures are compared with it, it is not regenerated by the build.

    python almanac_ref.py [--py DIR] [--eph DIR] [--out FILE]     # needs the network; a few minutes

Fetched (raw HTTP):
  - SIMBAD's TAP service (https://simbad.cds.unistra.fr/simbad/sim-tap/sync, ADQL over basic, ident, allfluxes, flux): for the Nautical Almanac's 57
    selected stars and Polaris, ICRS J2000 ra, dec (deg), pmra (mas/yr, with cos dec), pmdec, parallax (mas), radial velocity (km/s), V and the HIP
    number. A field SIMBAD leaves empty on the id asked for is taken from the entry in FILL (the system or the component) and named in "fill".
  - JPL Horizons' API (https://ssd.jpl.nasa.gov/api/horizons.api), observer tables (Venus 299 and Mars 499 too, quantity 2 and 20, at the epochs before 2050), TIME_TYPE UT, APPARENT AIRLESS, ANG_FORMAT DEG, EXTRA_PREC YES:
    geocentric (500@399) Sun (10) and Moon (301) quantity 2 (apparent RA/Dec: for Earth-based sites "with respect to the true-equator and Earth equinox
    of-date coordinate system (EOP-corrected IAU76/80 precession and nutation ...) and adjusted to model light-time, the gravitational deflection of
    light, and stellar aberration", Horizons manual), 20 (range: the Sun in au, the Moon in km), 23 (the Moon's S-O-T elongation), 30 (TDB-UT) and 49
    (UT1-UTC); topocentric (coord@399, GEODETIC) quantity 4 (apparent azimuth, elevation) at three sites.
Computed with skyfield (pip install --target DIR skyfield; --py DIR or ALMANAC_PY puts DIR on sys.path) and JPL's de440s.bsp (1849-2150, downloaded
into --eph DIR or ALMANAC_EPH, default ~/skyfield-data): the stars' geocentric apparent places of date (earth.at(t).observe(star).apparent()
.radec(epoch='date'), proper motion, parallax and radial velocity included) and GMST, GAST at each epoch, at UT1 = UTC + Horizons' UT1-UTC.

Times: "utc" is the time asked for (Horizons' UT: UT1 before 1962, UTC after); jd_ut is its JD. dT is TT - UT from Horizons' TDB-UT (less skyfield's
TDB - TT from 1962, when Horizons keeps the distinction); dut1 is UT1 - UTC (0 before 1962). Beyond its EOP predictions (about 78 days) Horizons holds
TT - UTC and UT1 - UTC constant, so its dT after 2026 stays near 69.2 s: an almanac checked against these Moon places must use this dT, not its own.
Epochs: 60 drawn from 1950-2149 and 30 from 2026-2035 by random.Random(SEED), whole minutes."""
import datetime as dt,json,math,os,pathlib,random,sys,time,urllib.parse,urllib.request
A=sys.argv[1:];opt=lambda k,env,d=None:A[A.index(k)+1] if k in A else os.environ.get(env,d)
PY=opt('--py','ALMANAC_PY');PY and sys.path.insert(0,PY)
from skyfield.api import Loader,Star;import skyfield
HERE=pathlib.Path(__file__).resolve().parent;OUT=pathlib.Path(opt('--out','ALMANAC_OUT',str(HERE/'almanac-ref.json')))
EPH=opt('--eph','ALMANAC_EPH',str(pathlib.Path.home()/'skyfield-data'))
STARS=[(1,'Alpheratz','alf And'),(2,'Ankaa','alf Phe'),(3,'Schedar','alf Cas'),(4,'Diphda','bet Cet'),(5,'Achernar','alf Eri'),(6,'Hamal','alf Ari'),
 (7,'Acamar','tet Eri'),(8,'Menkar','alf Cet'),(9,'Mirfak','alf Per'),(10,'Aldebaran','alf Tau'),(11,'Rigel','bet Ori'),(12,'Capella','alf Aur'),
 (13,'Bellatrix','gam Ori'),(14,'Elnath','bet Tau'),(15,'Alnilam','eps Ori'),(16,'Betelgeuse','alf Ori'),(17,'Canopus','alf Car'),(18,'Sirius','alf CMa'),
 (19,'Adhara','eps CMa'),(20,'Procyon','alf CMi'),(21,'Pollux','bet Gem'),(22,'Avior','eps Car'),(23,'Suhail','lam Vel'),(24,'Miaplacidus','bet Car'),
 (25,'Alphard','alf Hya'),(26,'Regulus','alf Leo'),(27,'Dubhe','alf UMa'),(28,'Denebola','bet Leo'),(29,'Gienah','gam Crv'),(30,'Acrux','alf01 Cru'),
 (31,'Gacrux','gam Cru'),(32,'Alioth','eps UMa'),(33,'Spica','alf Vir'),(34,'Alkaid','eta UMa'),(35,'Hadar','bet Cen'),(36,'Menkent','tet Cen'),
 (37,'Arcturus','alf Boo'),(38,'Rigil Kentaurus','alf Cen A'),(39,'Zubenelgenubi','alf02 Lib'),(40,'Kochab','bet UMi'),(41,'Alphecca','alf CrB'),
 (42,'Antares','alf Sco'),(43,'Atria','alf TrA'),(44,'Sabik','eta Oph'),(45,'Shaula','lam Sco'),(46,'Rasalhague','alf Oph'),(47,'Eltanin','gam Dra'),
 (48,'Kaus Australis','eps Sgr'),(49,'Vega','alf Lyr'),(50,'Nunki','sig Sgr'),(51,'Altair','alf Aql'),(52,'Peacock','alf Pav'),(53,'Deneb','alf Cyg'),
 (54,'Enif','eps Peg'),(55,"Al Na'ir",'alf Gru'),(56,'Fomalhaut','alf PsA'),(57,'Markab','alf Peg'),(0,'Polaris','alf UMi')]
FILL={'tet Eri':'tet01 Eri','alf01 Cru':'alf Cru','alf Cen A':'alf Cen'}   # where SIMBAD leaves a field empty: tet Eri has no V, alf01 Cru no parallax or HIP
SEED=1761;SITES=[(51.4769,-0.0005,46),(-33.86,151.21,0),(21.3,-157.86,0)]
APP=['1950-01-01 00:00','2000-01-01 12:00','2026-10-04 00:00','2040-06-15 06:00','2075-03-21 18:00','2120-09-01 00:00']
R=lambda x,n:None if x is None else round(x,n)
def get(url,data=None,tries=5):
    for k in range(tries):
        try:
            with urllib.request.urlopen(url,data,timeout=180) as f: return json.load(f)
        except Exception as e:
            if k==tries-1: raise
            print('  retry',k+1,e);time.sleep(5*(k+1))
def tap(q):
    r=get('https://simbad.cds.unistra.fr/simbad/sim-tap/sync',urllib.parse.urlencode({'request':'doQuery','lang':'adql','format':'json','query':q}).encode())
    c=[m['name'] for m in r['metadata']];return [dict(zip(c,row)) for row in r['data']]
def simbad(ids):   # one row per id asked for: astrometry, V (allfluxes, else flux V), the HIP number
    L="','".join(ids);rows=tap(f"""SELECT i.id AS q,b.main_id,b.ra,b.dec,b.pmra,b.pmdec,b.plx_value,b.rvz_radvel,a.V AS va,f.flux AS vf,h.id AS hip
 FROM basic AS b JOIN ident AS i ON i.oidref=b.oid LEFT JOIN allfluxes AS a ON a.oidref=b.oid LEFT JOIN flux AS f ON f.oidref=b.oid AND f.filter='V'
 LEFT JOIN ident AS h ON h.oidref=b.oid AND h.id LIKE 'HIP %' WHERE i.id IN ('{L}')""")
    n=lambda s:' '.join(s.replace('*','').split());out={}
    for r in rows:
        out[n(r['q'])]=dict(main=n(r['main_id']),ra=r['ra'],dec=r['dec'],pmra=r['pmra'],pmdec=r['pmdec'],plx=r['plx_value'],rv=r['rvz_radvel'],
          v=r['va'] if r['va'] is not None else r['vf'],hip=int(r['hip'].split()[1]) if r['hip'] else None)
    miss=[i for i in ids if n(i) not in out];assert not miss,f'SIMBAD has no {miss}';return {i:out[n(i)] for i in ids}
def stars():
    S=simbad([s[2] for s in STARS]+list(FILL.values()));res=[]
    for n,name,i in STARS:
        r=dict(S[i]);fill={}
        for k,v in r.items():
            if v is None and i in FILL and S[FILL[i]][k] is not None: r[k]=S[FILL[i]][k];fill[k]=FILL[i]
        e=dict(n=n,name=name,id=i,hip=r['hip'],ra=R(r['ra'],9),dec=R(r['dec'],9),pmra=r['pmra'],pmdec=r['pmdec'],plx=r['plx'],rv=r['rv'],v=r['v'])
        if fill: e['fill']=fill
        if r['v'] is None or r['v']>3.1 or None in (r['hip'],r['plx'],r['rv'],r['pmra']): print(f'  check {n} {name} ({i}): V {r["v"]}, HIP {r["hip"]}, plx {r["plx"]}, rv {r["rv"]}')
        res.append(e)
    return res
HZ='https://ssd.jpl.nasa.gov/api/horizons.api';SRC={}
def horizons(cmd,tl,center="'500@399'",q='2,20,30,49',extra={},N=20):   # rows of the CSV table, one per epoch of tl (calendar strings, UT), N epochs a request (a long TLIST gets a 502)
    if len(tl)>N: return [r for k in range(0,len(tl),N) for r in horizons(cmd,tl[k:k+N],center,q,extra,N)]
    p=dict(format='json',COMMAND=f"'{cmd}'",OBJ_DATA="'NO'",MAKE_EPHEM="'YES'",EPHEM_TYPE="'OBSERVER'",CENTER=center,TLIST=' '.join(f"'{t}'" for t in tl),
      TLIST_TYPE="'CAL'",TIME_TYPE="'UT'",QUANTITIES=f"'{q}'",ANG_FORMAT="'DEG'",EXTRA_PREC="'YES'",APPARENT="'AIRLESS'",CSV_FORMAT="'YES'",**extra)
    r=get(HZ+'?'+urllib.parse.urlencode(p));time.sleep(1.5);t=r['result']
    if '$$SOE' not in t: raise SystemExit('Horizons: '+t[-2000:])
    for ln in t.splitlines():
        if '{source:' in ln and 'Target body' in ln: SRC['eph']=ln.split('{source:')[1].strip(' }')
        if ln.startswith('EOP file'): SRC['eop']=ln.split(':',1)[1].strip()
    hd=t[:t.index('$$SOE')].splitlines()[-2];cols=[c.strip() for c in hd.split(',')]
    rows=[dict(zip(cols,[c.strip() for c in ln.split(',')])) for ln in t[t.index('$$SOE')+5:t.index('$$EOE')].strip().splitlines()]
    assert len(rows)==len(tl),(len(rows),len(tl));return rows
f=lambda s:None if s in ('n.a.','') else float(s)
def epochs():
    g=random.Random(SEED);a=dt.datetime(1950,1,1);mins=lambda d0,d1:g.randrange(int((d1-d0).total_seconds()//60))
    E=sorted(a+dt.timedelta(minutes=mins(a,dt.datetime(2150,1,1))) for _ in range(60))
    b=dt.datetime(2026,1,1);E+=sorted(b+dt.timedelta(minutes=mins(b,dt.datetime(2036,1,1))) for _ in range(30));return E
iso=lambda d:d.strftime('%Y-%m-%dT%H:%M');cal=lambda d:d.strftime('%Y-%m-%d %H:%M')
def jd(d): return (d-dt.datetime(2000,1,1,12)).total_seconds()/86400+2451545.0
def main():
    ld=Loader(EPH,verbose=False);ts=ld.timescale();eph=ld('de440s.bsp');earth=eph['earth']
    print('SIMBAD ...');st=stars()
    print('stars apparent ...');sa=[]
    for u in APP:
        d=dt.datetime.fromisoformat(u);t=ts.utc(d.year,d.month,d.day,d.hour,d.minute);ra,dec=[],[]
        for s in st:
            S=Star(ra_hours=s['ra']/15,dec_degrees=s['dec'],ra_mas_per_year=s['pmra'] or 0,dec_mas_per_year=s['pmdec'] or 0,parallax_mas=s['plx'] or 0,radial_km_per_s=s['rv'] or 0)
            a,de,_=earth.at(t).observe(S).apparent().radec(epoch='date');ra.append(R(a._degrees,7));dec.append(R(de.degrees,7))
        sa.append(dict(utc=iso(d),jd_ut=R(jd(d),6),jd_tt=R(t.tt,8),ra=ra,dec=dec))
    E=epochs();tl=[cal(d) for d in E];print('Horizons geocentric ...')
    sun=horizons('10',tl);moon=horizons('301',tl,q='2,20,23',extra=dict(RANGE_UNITS="'KM'"))
    ep=[]
    for d,s,m in zip(E,sun,moon):
        assert s['Date__(UT)__HR:MN:SC.fff'].startswith(d.strftime('%Y-%b-%d %H:%M')),s
        tdbut=f(s['TDB-UT']);du=f(s['UT1-UTC']) or 0.0;j=jd(d)
        t=ts.utc(d.year,d.month,d.day,d.hour,d.minute);dT=tdbut-((t.tdb-t.tt)*86400 if d.year>=1962 else 0)
        tu=ts.ut1_jd(j+du/86400)
        ep.append(dict(utc=iso(d),jd_ut=R(j,6),dT=R(dT,3),dut1=R(du,4),gmst=R(tu.gmst,10),gast=R(tu.gast,10),
          sun=dict(ra=R(f(s['R.A.__(a-app)']),7),dec=R(f(s['DEC___(a-app)']),7),au=R(f(s['delta']),9)),
          moon=dict(ra=R(f(m['R.A.__(a-app)']),7),dec=R(f(m['DEC___(a-app)']),7),km=R(f(m['delta']),3)),elong=f(m['S-O-T'])))
    print('Horizons topocentric ...');tp=[];rec=E[60:]
    for i,(la,lo,h) in enumerate(SITES):
        D=[rec[(i*9+k)%30] for k in range(12)];D.sort();tl=[cal(d) for d in D]
        x=dict(COORD_TYPE="'GEODETIC'",SITE_COORD=f"'{lo},{la},{h/1000}'");a=horizons('10',tl,"'coord@399'",'4',x);b=horizons('301',tl,"'coord@399'",'4',x)
        for d,s,m in zip(D,a,b):
            az=lambda r:dict(az=R(f(r['Azimuth_(a-app)']),7),el=R(f(r['Elevation_(a-app)']),7))
            tp.append(dict(site=[la,lo,h],utc=iso(d),jd_ut=R(jd(d),6),sun=az(s),moon=az(m)))
    print('Horizons planets ...');PE=sorted(d for d in E if d.year<2050);   # in time order: Horizons returns a request's rows sorted
    tl=[cal(d) for d in PE]   # Venus and Mars, within JPL's approximate elements' 1800-2050
    ve=horizons('299',tl,q='2,20');ma=horizons('499',tl,q='2,20');pl=[]
    byu={e['utc']:e for e in ep}
    for d,v,m in zip(PE,ve,ma):
        for r in (v,m):assert r['Date__(UT)__HR:MN:SC.fff'].startswith(d.strftime('%Y-%b-%d %H:%M')),r
        e=byu[iso(d)];pa=lambda r:dict(ra=R(f(r['R.A.__(a-app)']),7),dec=R(f(r['DEC___(a-app)']),7),au=R(f(r['delta']),9))
        pl.append(dict(utc=iso(d),jd_ut=e['jd_ut'],dT=e['dT'],dut1=e['dut1'],venus=pa(v),mars=pa(m)))
    out=dict(made=dt.date.today().isoformat(),sources=[f"JPL Horizons API (observer tables, {SRC.get('eph','?')}, EOP {SRC.get('eop','?')})",
      'SIMBAD TAP (basic, ident, allfluxes/flux V), ICRS J2000',f'skyfield {skyfield.__version__}','JPL de440s.bsp'],
      notes='angles in degrees, gmst/gast in hours, dT = TT-UT and dut1 = UT1-UTC in seconds; Horizons apparent places are airless, true equator and equinox of date',
      stars=st,stars_apparent=sa,epochs=ep,topo=tp,planets=pl)
    OUT.write_text(json.dumps(out,separators=(',',':'),ensure_ascii=False)+'\n',encoding='utf-8');print('wrote',OUT,OUT.stat().st_size,'bytes')
if __name__=='__main__': main()
