"""Writes BOM.md, the parts list against the model, from a bom.py run (python bom.py --md). Generated: edit bom.json or the model, not BOM.md."""
import re
FIG={'106':'Fig. 106: mounting box and gimbals','107':'Fig. 107: case, dial and motion work','108':'Fig. 108: balance, cock, setup and barrel bridge',
     '109':'Fig. 109: barrel and fusee','110':'Fig. 110: escapement, train, bridges and pillar plate'}
def fig_of(l,L):
    k=l
    while k:
        if k.get('idx'):return k['idx'].split('-')[0]
        k=L.get(k.get('parent'))
    return None
def cell(t):return str(t).replace('|','/').replace('\n',' ')
def rel_txt(r):
    k=r['kind']
    if r.get('err'):return f"{k} {r['tgt']}: {r['err']}"
    if k in('in','round'):
        g=r.get('gabs');fit=r.get('fit')
        return f"{'in' if k=='in' else 'round'} {r['tgt']} ({r['how']}): {fit if fit is not None else r['len']} mm, least gap {g}"
    if k=='on':return f"on {r['tgt']}: {r['d']} mm"
    if k=='mesh':return f"meshes {r['tgt']}: centres {r['d']} (m(z1+z2)/2 {r['want']}), {r['za']}/{r['zb']} teeth, faces overlap {r['ov']}, ratio {r['ratio']}"
    if k=='endshake':return f"endshake {r['dial'][0]+r['train'][0]:.3f} mm ({r['dial'][1]} / {r['train'][1]})"
    return k
def write(BOM,res,F,D,path):
    L={l['id']:l for l in BOM['lines']};bad={}
    for f in F:
        m=re.match(r'(?:count |in |round |on |mesh |endshake |jewel )?([\w.]+)',f)
        if m:bad.setdefault(m.group(1).split('#')[0],[]).append(f)
    rel={}
    for r in res['rel']:rel.setdefault(r['id'],[]).append(r)
    out=['# The parts list against the model','',
      'Generated by `marine-chronometer-source/chronometer-working-model/tools/bom.py --md` from `bom.json` (the manual\'s Sec. XI Maintenance Parts Catalog, Figs. 106-110, pp. 78-88, its totals checked against the Sec. XII numerical list, p. 89) and measurements of the built model. Do not edit by hand.','',
      f"**Status:** {sum(1 for l in BOM['lines'] if l['kind'] in('part','jewel'))} lines counted, {len(res['rel'])} relations measured, {len(res['jewels'])} jewels; "+(f"**{len(F)} failures**" if F else 'no failures')+(f", {len(D)} known deviation(s)" if D else '')+'.','',
      'Columns: the manual\'s index and Hamilton number, its units per chronometer, the pieces in the model, the part card it belongs to, what the part does (with its source), and how it goes into the mechanism as measured: `in` a thread, pivot, pin or setting inside the named part (tap, clear, run, free, press, or embed where a hole across an extrusion or turned part is not cut), `round` a bore round the named part, `on` the least distance to the part it rests on, `meshes` the gear check, `endshake` the axial play (0.001-0.003 in, Ops. 15, 69, 74). The last column is the check\'s verdict.','']
    order=['106','107','108','109','110']
    for fg in order:
        out+=[f'## {FIG[fg]}','','| Idx | No. | Name | Manual | Model | Card | Function | Fit and drive (measured) | |','|---|---|---|---|---|---|---|---|---|']
        for l in BOM['lines']:
            if l['kind'] not in('part','jewel') or fig_of(l,L)!=fg:continue
            n=res['counts'].get(l['id'],0);q=l['qty'];qs=f"{q[0]}-{q[1]}" if isinstance(q,list) else q
            rs='<br>'.join(rel_txt(r)+('' if r['i']==0 or len(rel[l['id']])<4 else f" (#{r['i']})") for r in rel.get(l['id'],[]) if r['i']==0)
            if l.get('check'):rs+=('<br>' if rs else '')+f"also: {l['check']}"
            v='✗' if l['id'] in bad else '✓'
            if l.get('dev'):v+=' (deviation)'
            out.append(f"| {l.get('idx') or ''} | {l.get('no') or ''} | {cell(l['name'])} | {qs} | {n} | {l.get('part') or ''} | {cell(l['fn'])} | {cell(rs)} | {v} |")
        out.append('')
    out+=['## The fourteen jewels (Sec. II, Jeweling)','','| Jewel | Kind | Arbor, end | Set in | Least gap |','|---|---|---|---|---|']
    for j in res['jewels']:out.append(f"| {cell(L[j['id']]['name'])} | {j['type']} | {j.get('arbor') or ''} {j.get('end') or ''} | {', '.join(f'{k} ({n} mm)' for k,n in j['by'][:2])} | {j['gmin']} |")
    out+=['','## The gears as meshed','','| Driver | Driven | Teeth | Modules | Centres | m(z1+z2)/2 | Faces overlap | Ratio | Want |','|---|---|---|---|---|---|---|---|---|']
    for g in res['gears']:out.append(f"| {g['a']} | {g['b']} | {g['za']}/{g['zb']} | {g['ma']}/{g['mb']} | {g['d']} | {g['want']} | {g['ov']} | {g['ratio']} | {g['wantRatio']} |")
    out+=['','## Not modelled, and why','','| No. | Name | Why |','|---|---|---|']
    for l in BOM['lines']:
        if l['kind'] in('ref','variant','omit'):out.append(f"| {l.get('no')} | {cell(l['name'])} | {cell(l.get('why') or {'ref':'superseded or reference only (p. 88)','variant':'an alternative size (p. 88)'}.get(l['kind'],''))} |")
    if D:out+=['','## Known deviations','']+[f'- {d}' for d in D]
    if F:out+=['','## Open failures','']+[f'- {cell(f)}' for f in F]
    path.write_text('\n'.join(out)+'\n',encoding='utf-8',newline='\n')
